left_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - L1_joint
    - L2_joint
    - L3_joint
    - L4_joint
    - L5_joint
    - L6_joint
    - L7_joint
  gains:
    L1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L7_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - R1_joint
    - R2_joint
    - R3_joint
    - R4_joint
    - R5_joint
    - R6_joint
    - R7_joint
  gains:
    R1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R7_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1