controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - L1_joint
      - L2_joint
      - L3_joint
      - L4_joint
      - L5_joint
      - L6_joint
      - L7_joint
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - R1_joint
      - R2_joint
      - R3_joint
      - R4_joint
      - R5_joint
      - R6_joint
      - R7_joint